// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// de1nrmC
Rcpp::NumericVector de1nrmC(List PITEML, Rcpp::NumericVector nodes, NumericMatrix FIQ, NumericMatrix RIQ);
RcppExport SEXP mcIRT_de1nrmC(SEXP PITEMLSEXP, SEXP nodesSEXP, SEXP FIQSEXP, SEXP RIQSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< List >::type PITEML(PITEMLSEXP );
        Rcpp::traits::input_parameter< Rcpp::NumericVector >::type nodes(nodesSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type FIQ(FIQSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type RIQ(RIQSEXP );
        Rcpp::NumericVector __result = de1nrmC(PITEML, nodes, FIQ, RIQ);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// EnrmC
List EnrmC(List PITEMLL, List NODW, List Yl, List NU1);
RcppExport SEXP mcIRT_EnrmC(SEXP PITEMLLSEXP, SEXP NODWSEXP, SEXP YlSEXP, SEXP NU1SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< List >::type PITEMLL(PITEMLLSEXP );
        Rcpp::traits::input_parameter< List >::type NODW(NODWSEXP );
        Rcpp::traits::input_parameter< List >::type Yl(YlSEXP );
        Rcpp::traits::input_parameter< List >::type NU1(NU1SEXP );
        List __result = EnrmC(PITEMLL, NODW, Yl, NU1);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
