// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// de1nrmC
Rcpp::NumericVector de1nrmC(List PITEMLL, List QUADS, List fiqG, List riqv_querG);
RcppExport SEXP mcIRT_de1nrmC(SEXP PITEMLLSEXP, SEXP QUADSSEXP, SEXP fiqGSEXP, SEXP riqv_querGSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< List >::type PITEMLL(PITEMLLSEXP );
        Rcpp::traits::input_parameter< List >::type QUADS(QUADSSEXP );
        Rcpp::traits::input_parameter< List >::type fiqG(fiqGSEXP );
        Rcpp::traits::input_parameter< List >::type riqv_querG(riqv_querGSEXP );
        Rcpp::NumericVector __result = de1nrmC(PITEMLL, QUADS, fiqG, riqv_querG);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// EnrmC
List EnrmC(List PITEMLL, List NODW, List Yl, List NU1);
RcppExport SEXP mcIRT_EnrmC(SEXP PITEMLLSEXP, SEXP NODWSEXP, SEXP YlSEXP, SEXP NU1SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< List >::type PITEMLL(PITEMLLSEXP );
        Rcpp::traits::input_parameter< List >::type NODW(NODWSEXP );
        Rcpp::traits::input_parameter< List >::type Yl(YlSEXP );
        Rcpp::traits::input_parameter< List >::type NU1(NU1SEXP );
        List __result = EnrmC(PITEMLL, NODW, Yl, NU1);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
