# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

de1nrmC <- function(PITEML, nodes, FIQ, RIQ) {
    .Call('mcIRT_de1nrmC', PACKAGE = 'mcIRT', PITEML, nodes, FIQ, RIQ)
}

EnrmC <- function(PITEMLL, NODW, Yl, NU1) {
    .Call('mcIRT_EnrmC', PACKAGE = 'mcIRT', PITEMLL, NODW, Yl, NU1)
}

